### ISSUE TITLE
X-EconomicAppIdentifier header

### ISSUE THREAD

**Issue by prognostikos** [substancelab/rconomic#41]
According to http://techtalk.e-conomic.com/e-conomic-soap-api-now-requires-you-to-specify-a-custom-x-economicappidentifier-header/ e-conomic is now requiring a custom header for API users.

From what I can see, we would have to modify `Econonmic::Endpoint#client` to set this header.

Has anyone run into trouble with this or is there another way to add the header or do a workaround that I'm missing?

**Comment by prognostikos** [comment]
On further reading, I guess this only applies if you use the `connect_with_credentials` method, and not the `connect_with_token` method.

**Comment by koppen** [comment]
As detailed in #39 the current recommendation (from E-conomic) is to use `connect_with_token`. I guess that's in the workaround category and I definitely wouldn't mind a pull request adding the header.

I suspect adding it to all requests would be fine, even if not using `connect_with_credentials`.

**Comment by prognostikos** [comment]
Er, derp, forgot to search for old issues :/

Will look into the PR as on first glance it seems that all the ceremony around `connect_with_token` doesn't make a ton of sense for internal apps.

**Comment by prognostikos** [comment]
There's an attempt at this in #42

**Comment by prognostikos** [comment]
Closing as #42 has been merged
