### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by askehansen** [substancelab/rconomic#43]
Is there any reason the latest version is from march 2014?
It seems to be very inconsistent with the readme

**Comment by nielsbuus** [comment]
Hello Aske

We are no longer maintaining this repository which was originally created by @koppen , a previous team member.

I think he has the credentials to release a new version on Ruby Gems.

**Comment by koppen** [comment]
Newest released version is 0.6.0, released on April 30th. Changelog is at https://github.com/substancelab/rconomic/blob/master/CHANGELOG.md#060-april-30-2017.
